### ISSUE TITLE
Roadmap

### ISSUE THREAD

**Issue by haikyuu** [haikyuu/perfect-stack#1]
This project is intended to be used as a starter projects for rapid development.

# Roadmap
- [x] Complete Ping CRM functionality
  - [x] Manage Contacts
  - [x] Manage users (contains upload)
- [x] Polish the API of inertia adapters for Imba
- [x] Polish the API of inertia express adapter
- [x] Add tests
- [ ] Deploy to the cloud
